"""Replenishment Recommendation model."""

from sqlalchemy import Column, Integer, ForeignKey, String, Date, Float, Text
from sqlalchemy.orm import relationship

from app.core.database import Base
from app.models.base import TimeStampMixin


class ReplenishmentRecommendation(Base, TimeStampMixin):
    """
    Stores evidence-backed replenishment suggestions generated by the planning services.
    """

    __tablename__ = "replenishment_recommendations"

    id = Column(Integer, primary_key=True, index=True)
    material_id = Column(
        Integer,
        ForeignKey("materials.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    plant_id = Column(
        Integer,
        ForeignKey("plants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    recommendation_type = Column(String(50), nullable=False)  # Replenish, Expedite Existing PO, Transfer Between Plants, Restore Safety Stock, Increase Future Procurement
    quantity = Column(Integer, nullable=False)
    order_date = Column(Date, nullable=False)
    eta_date = Column(Date, nullable=False)

    # Optional references
    source_plant_id = Column(
        Integer,
        ForeignKey("plants.id", ondelete="SET NULL"),
        nullable=True,
    )
    target_supplier_id = Column(
        Integer,
        ForeignKey("suppliers.id", ondelete="SET NULL"),
        nullable=True,
    )

    reason = Column(Text, nullable=False)
    evidence = Column(Text, nullable=False)  # Detail why, e.g., JSON or description
    confidence = Column(Float, nullable=False, default=1.0)  # 0.0 to 1.0
    priority = Column(String(20), nullable=False, default="MEDIUM")  # LOW, MEDIUM, HIGH, CRITICAL
    status = Column(String(20), nullable=False, default="NEW")  # NEW, APPROVED, REJECTED, PROCESSED

    # Relationships
    material = relationship("Material", lazy="selectin")
    plant = relationship("Plant", foreign_keys=[plant_id], lazy="selectin")
    source_plant = relationship("Plant", foreign_keys=[source_plant_id], lazy="selectin")
    supplier = relationship("Supplier", lazy="selectin")

    def __repr__(self):
        return f"<ReplenishmentRecommendation type={self.recommendation_type} material={self.material_id} qty={self.quantity}>"
