"""add_unique_constraint_material_projection

Revision ID: 64e3a8a43d92
Revises: 20260313_notifications
Create Date: 2026-07-16 11:34:02.915316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64e3a8a43d92'
down_revision: Union[str, None] = '20260313_notifications'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_customer_id', table_name='sales')
    op.drop_index('ix_sales_id', table_name='sales')
    op.drop_index('ix_sales_invoice_number', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_sale_items_id', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index('ix_customers_city', table_name='customers')
    op.drop_index('ix_customers_company_name', table_name='customers')
    op.drop_index('ix_customers_customer_code', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_index('ix_customers_full_name', table_name='customers')
    op.drop_index('ix_customers_id', table_name='customers')
    op.drop_index('ix_customers_is_active', table_name='customers')
    op.drop_index('ix_customers_phone', table_name='customers')
    op.drop_table('customers')
    op.create_unique_constraint('uq_projection_mat_plant_date', 'material_projections', ['material_id', 'plant_id', 'date'])
    op.add_column('stock_adjustments', sa.Column('material_id', sa.Integer(), nullable=False))
    op.add_column('stock_adjustments', sa.Column('plant_id', sa.Integer(), nullable=False))
    op.drop_index('ix_stock_adjustments_product_id', table_name='stock_adjustments')
    op.drop_index('ix_stock_adjustments_warehouse_id', table_name='stock_adjustments')
    op.create_index('ix_stock_adjustments_material_id', 'stock_adjustments', ['material_id'], unique=False)
    op.create_index('ix_stock_adjustments_plant_id', 'stock_adjustments', ['plant_id'], unique=False)
    op.create_foreign_key(None, 'stock_adjustments', 'plants', ['plant_id'], ['id'])
    op.create_foreign_key(None, 'stock_adjustments', 'materials', ['material_id'], ['id'])
    op.drop_column('stock_adjustments', 'warehouse_id')
    op.drop_column('stock_adjustments', 'product_id')
    op.add_column('stock_ledger', sa.Column('material_id', sa.Integer(), nullable=False))
    op.add_column('stock_ledger', sa.Column('plant_id', sa.Integer(), nullable=False))
    op.drop_index('ix_stock_ledger_product_id', table_name='stock_ledger')
    op.drop_index('ix_stock_ledger_warehouse_id', table_name='stock_ledger')
    op.create_index(op.f('ix_stock_ledger_material_id'), 'stock_ledger', ['material_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_plant_id'), 'stock_ledger', ['plant_id'], unique=False)
    op.create_foreign_key(None, 'stock_ledger', 'materials', ['material_id'], ['id'])
    op.create_foreign_key(None, 'stock_ledger', 'plants', ['plant_id'], ['id'])
    op.drop_column('stock_ledger', 'warehouse_id')
    op.drop_column('stock_ledger', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_ledger', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stock_ledger', sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stock_ledger', type_='foreignkey')
    op.drop_constraint(None, 'stock_ledger', type_='foreignkey')
    op.drop_index(op.f('ix_stock_ledger_plant_id'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_material_id'), table_name='stock_ledger')
    op.create_index('ix_stock_ledger_warehouse_id', 'stock_ledger', ['warehouse_id'], unique=False)
    op.create_index('ix_stock_ledger_product_id', 'stock_ledger', ['product_id'], unique=False)
    op.drop_column('stock_ledger', 'plant_id')
    op.drop_column('stock_ledger', 'material_id')
    op.add_column('stock_adjustments', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stock_adjustments', sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stock_adjustments', type_='foreignkey')
    op.drop_constraint(None, 'stock_adjustments', type_='foreignkey')
    op.drop_index('ix_stock_adjustments_plant_id', table_name='stock_adjustments')
    op.drop_index('ix_stock_adjustments_material_id', table_name='stock_adjustments')
    op.create_index('ix_stock_adjustments_warehouse_id', 'stock_adjustments', ['warehouse_id'], unique=False)
    op.create_index('ix_stock_adjustments_product_id', 'stock_adjustments', ['product_id'], unique=False)
    op.drop_column('stock_adjustments', 'plant_id')
    op.drop_column('stock_adjustments', 'material_id')
    op.drop_constraint('uq_projection_mat_plant_date', 'material_projections', type_='unique')
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('customers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('customer_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('customer_type', postgresql.ENUM('INDIVIDUAL', 'BUSINESS', name='customertype'), autoincrement=False, nullable=False),
    sa.Column('credit_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='customers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.create_index('ix_customers_is_active', 'customers', ['is_active'], unique=False)
    op.create_index('ix_customers_id', 'customers', ['id'], unique=False)
    op.create_index('ix_customers_full_name', 'customers', ['full_name'], unique=False)
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_index('ix_customers_customer_code', 'customers', ['customer_code'], unique=True)
    op.create_index('ix_customers_company_name', 'customers', ['company_name'], unique=False)
    op.create_index('ix_customers_city', 'customers', ['city'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('discount_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name='sale_items_sale_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sale_items_pkey')
    )
    op.create_index('ix_sale_items_id', 'sale_items', ['id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('sale_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='salestatus'), autoincrement=False, nullable=False),
    sa.Column('payment_method', postgresql.ENUM('CASH', 'CARD', 'BANK_TRANSFER', 'MOBILE_PAYMENT', 'OTHER', name='paymentmethod'), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tax_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('paid_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_sales_customer_id_customers', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='sales_customer_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sales_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sales_pkey')
    )
    op.create_index('ix_sales_invoice_number', 'sales', ['invoice_number'], unique=True)
    op.create_index('ix_sales_id', 'sales', ['id'], unique=False)
    op.create_index('ix_sales_customer_id', 'sales', ['customer_id'], unique=False)
    # ### end Alembic commands ###
